// Canonical section IDs exposed by LibreClaw system prompt customization.
export const SYSTEM_PROMPT_SECTION_IDS = [
  "tooling",
  "subagent_delegation",
  "interaction_style",
  "tool_call_style",
  "execution_bias",
  "safety",
  "openclaw_control",
  "skills",
  "skill_workshop",
  "memory_recall",
  "openclaw_self_update",
  "model_aliases",
  "workspace",
  "documentation",
  "sandbox",
  "workspace_files_injected",
  "reasoning_format",
  "assistant_output_directives",
  "control_ui_embed",
  "project_context",
  "dynamic_project_context",
  "silent_replies",
  "group_chat_context",
  "subagent_context",
  "reactions",
  "runtime",
  "heartbeats",
  "authorized_senders",
  "current_date_time",
  "voice_tts",
  "bootstrap_pending",
  "bootstrap_context_notice",
] as const;

export type SystemPromptSectionId = (typeof SYSTEM_PROMPT_SECTION_IDS)[number];
